services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest # Use the Kali Linux image
    container_name: kali-linux # Name the container
    environment:
      - PUID=1000 # User ID
      - PGID=1000 # Group ID
      - TZ=Etc/UTC # Timezone
      - SUBFOLDER=/ # Optional
      - TITLE="Kali Linux" # Optional
    ports:
      - "3000:3000" # Map port 3000
      - "3001:3001" # Map port 3001
    devices:
      - /dev/dri:/dev/dri # GPU access (optional)
    shm_size: "1gb" # Shared memory size
    restart: unless-stopped # Restart policy
    volumes:
      - ./your-local-folder:/home/bind # Bind mount; change to your desired path
    command: >
      /bin/bash -c "
        apt update && \
        apt install -y ghidra  && \  # Replace with your desired software
        <additional_commands>  # Add any other commands you want to run
        tail -f /dev/null"  # Keep the container running
